/*
 * File:                CategorySelect.java
 * Author:              Andre Smink
 * Date:                November 2012
 * Operating System:    Windows 7 64-bit
 * Description:         Creates a user interface to allow users to select a category
 *                      and start the game
 */
package hangman;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.Random;
import javax.swing.AbstractAction;
import javax.swing.KeyStroke;

/**
 *
 * @author Sminky
 */
public class CategorySelect extends javax.swing.JFrame {

    //Game class to start the game
    Game game = null;
    //DatabaseConnection class to connect to the database
    DataRetrieval dataRetrieval = null;
    //Menu class to return to the main menu
    Menu menu = null;
    //ID of the category the use chose
    String catID;
    Loader loader = null;

    /**
     * Creates new form CategorySelect
     */
    public CategorySelect() {
        //create GUI
        initComponents();
        //Set location of window to th center of the screen
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cats = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        drinks = new javax.swing.JRadioButton();
        movies = new javax.swing.JRadioButton();
        actors = new javax.swing.JRadioButton();
        myth = new javax.swing.JRadioButton();
        series = new javax.swing.JRadioButton();
        cars = new javax.swing.JRadioButton();
        games = new javax.swing.JRadioButton();
        hist = new javax.swing.JRadioButton();
        sport = new javax.swing.JRadioButton();
        random = new javax.swing.JRadioButton();
        startButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        titleLabel.setFont(new java.awt.Font("Eraser", 0, 14)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Select a Category to Play");
        titleLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setName("JHgdfg"); // NOI18N

        drinks.setBackground(new java.awt.Color(0, 0, 0));
        cats.add(drinks);
        drinks.setFont(new java.awt.Font("Eraser", 0, 14)); // NOI18N
        drinks.setForeground(new java.awt.Color(255, 255, 255));
        drinks.setSelected(true);
        drinks.setText("Drinks");

        movies.setBackground(new java.awt.Color(0, 0, 0));
        cats.add(movies);
        movies.setFont(new java.awt.Font("Eraser", 0, 14)); // NOI18N
        movies.setForeground(new java.awt.Color(255, 255, 255));
        movies.setText("Movies");

        actors.setBackground(new java.awt.Color(0, 0, 0));
        cats.add(actors);
        actors.setFont(new java.awt.Font("Eraser", 0, 14)); // NOI18N
        actors.setForeground(new java.awt.Color(255, 255, 255));
        actors.setText("Actors/Actresses");

        myth.setBackground(new java.awt.Color(0, 0, 0));
        cats.add(myth);
        myth.setFont(new java.awt.Font("Eraser", 0, 14)); // NOI18N
        myth.setForeground(new java.awt.Color(255, 255, 255));
        myth.setText("Mythology");

        series.setBackground(new java.awt.Color(0, 0, 0));
        cats.add(series);
        series.setFont(new java.awt.Font("Eraser", 0, 14)); // NOI18N
        series.setForeground(new java.awt.Color(255, 255, 255));
        series.setText("Series");

        cars.setBackground(new java.awt.Color(0, 0, 0));
        cats.add(cars);
        cars.setFont(new java.awt.Font("Eraser", 0, 14)); // NOI18N
        cars.setForeground(new java.awt.Color(255, 255, 255));
        cars.setText("Cars");

        games.setBackground(new java.awt.Color(0, 0, 0));
        cats.add(games);
        games.setFont(new java.awt.Font("Eraser", 0, 14)); // NOI18N
        games.setForeground(new java.awt.Color(255, 255, 255));
        games.setText("Games");

        hist.setBackground(new java.awt.Color(0, 0, 0));
        cats.add(hist);
        hist.setFont(new java.awt.Font("Eraser", 0, 14)); // NOI18N
        hist.setForeground(new java.awt.Color(255, 255, 255));
        hist.setText("Historical People");

        sport.setBackground(new java.awt.Color(0, 0, 0));
        cats.add(sport);
        sport.setFont(new java.awt.Font("Eraser", 0, 14)); // NOI18N
        sport.setForeground(new java.awt.Color(255, 255, 255));
        sport.setText("Sport");

        random.setBackground(new java.awt.Color(0, 0, 0));
        cats.add(random);
        random.setFont(new java.awt.Font("Eraser", 0, 14)); // NOI18N
        random.setForeground(new java.awt.Color(255, 255, 255));
        random.setText("Random");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(drinks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(movies, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(actors, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(myth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(series, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cars, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(games, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(random, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(drinks)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(movies)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(actors)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(myth)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(series)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cars)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(games)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hist)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(random)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        startButton.setText("START");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });
        startButton.getInputMap(startButton.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0), "startButton");
        startButton.getActionMap().put("startButton", new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                startButtonActionPerformed(e);  // some function
            }
        });

        backButton.setText("BACK");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(backButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed

        if (loader == null) {
            loader = new Loader();
        }
        loader.setVisible(true);

        //Set the frame invisible
        setVisible(false);
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                //Assign id of selected category to catID
                catID = "";
                if (drinks.isSelected()) {
                    catID = "Drinks";
                } else if (movies.isSelected()) {
                    catID = "Movies";
                } else if (actors.isSelected()) {
                    catID = "Actors";
                } else if (myth.isSelected()) {
                    catID = "Myth";
                } else if (series.isSelected()) {
                    catID = "Series";
                } else if (hist.isSelected()) {
                    catID = "People";
                } else if (sport.isSelected()) {
                    catID = "Sport";
                } else if (cars.isSelected()) {
                    catID = "Cars";
                } else if (games.isSelected()) {
                    catID = "Games";
                } else if (random.isSelected()) {
                    String catsArr[] = {"Drinks", "Movies", "Actors", "Myth", "Series", "People", "Sport", "Games"};

                    Random r = new Random();

                    int index = r.nextInt(7);

                    catID = catsArr[index];

                    System.out.println(catID);
                }

                //Create object of dataRetrieval if it doesn't exist yet
                if (dataRetrieval == null) {
                    dataRetrieval = new DataRetrieval();
                }

                //Create object of game if it doesn't exist yet
                if (game == null) {
                    game = new Game();
                }

                String word = dataRetrieval.getWord(catID);

                loader.setVisible(false);

                game.startGame(word, true);
            }
        });
    }//GEN-LAST:event_startButtonActionPerformed

    //Action for the back button that takes you back to the main menu
    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        //Create object of Menu class if it doesn't exist
        if (menu == null) {
            menu = new Menu();
        }
        //set menu visible
        menu.setVisible(true);
        //set frame invisible
        setVisible(false);
    }//GEN-LAST:event_backButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton actors;
    private javax.swing.JButton backButton;
    private javax.swing.JRadioButton cars;
    private javax.swing.ButtonGroup cats;
    private javax.swing.JRadioButton drinks;
    private javax.swing.JRadioButton games;
    private javax.swing.JRadioButton hist;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton movies;
    private javax.swing.JRadioButton myth;
    private javax.swing.JRadioButton random;
    private javax.swing.JRadioButton series;
    private javax.swing.JRadioButton sport;
    private javax.swing.JButton startButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
